type: content-markdown
title: 单向数据流驱动的游戏 UI
author: NaNuNoo
date: 2016-09-13
preMarkdown:
  站在开发者的角度，游戏是什么？抛开 Journey、纪念碑谷一类高度艺术化的作品不谈，游戏就是一套 2D/3D 的核心玩法 + 一大堆 UI，这在页游与手游领域尤其明显，且呈现越坑钱 UI 越多的规律。

  游戏开发中困难又有趣的技术集中在核心玩法，渲染、物理、AI、寻路、地形……一般人对游戏开发者的印象大都基于此。甚至一部分程序员以游戏程序自居，干着 UI 的活，却对这些年 APP UI 架构的快速演进视而不见。

  近些年，APP 开发经历了 MVC、MVVM、数据驱动等阶段，光 Web 领域就产生了许多诸如 Angular、Vue、React 等优秀的应用框架，其中的设计思想尤其值得借鉴。本文基于当前流行的 Redux，讨论如何在游戏 UI 中引入单向数据流驱动的开发模式。
