type: content-markdown
title: HTML5 音频踩坑
author: NaNuNoo
date: 2016-08-10
preMarkdown:
  这篇文章中的内容是 HTML5 音频库实现一文内容的先行研究。按理来说先行研究没有必要整理成文，因为没有太多值得记录的内容。然而 HTML5 音频库各种各样的问题实在令人发指，才有了这篇文章，帮助后人快速地爬出这些坑。

  HTML5 原生支持音频播放有一段时间了，有 Audio 元素和 WebAdio 两套音频相关的 API，针对不同的应用场景设计。

  Audio 元素支持音频文件播放，针对音乐类多媒体。出现时间较早，浏览器的支持也较好。

  WebAudio 支持音频编解码，支持音效混合，针对游戏类、音频处理类应用。还比较新，移动浏览器支持稍差。

  对于游戏引擎，通行的做法是优先使用 WebAudio API，并支 Audio 元素作为降级处理。但是，和多数 HTML5 新特性一样，Audio 元素和 WebAudio 也有非常严重的兼容性问题，以下总结了 FenQi.Engine开发过程中遇到的坑，附带我们的解决办法。
