type: content-markdown
title: HTML5 音频库实现
author: NaNuNoo
date: 2016-08-30
preMarkdown:
  音频是游戏中不可或缺的重要组成部分。虽然音频库的实现不如图形库那么复杂，但是对比还算丰富的 WebGL 资料和图形库实现，HTML5 音频库的资料与实现方面的资料明显缺乏。

  本文介绍如何实现一个针对 2D 游戏的音频库，可以播放 BGM、音效和人物对话，尽量做到播放流程无卡顿，均衡网络传输与内存、CPU 占用。

  音频库还提供两个额外功能：音频打包（Sound Sprite），BGM 与游戏动画同步的功能。

  音频库对于运行环境的最低要求是支持 Audio 元素（要求不同 Audio 元素能够同时播放不同音频）。为了达到最优的效果，WebAudio 的支持必不可少。
